# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin "vagrant-windows"

Vagrant.configure("2") do |config|
  config.vm.box = "win7x64pro"
  config.vm.guest = :windows
  config.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07NE00OEQyYnoySDg/"
  #VMWare version
  #config.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07WW1LamJzakt2MUE/"

  config.windows.halt_timeout = 20

  config.vm.provider :virtualbox do |v|
    # Don't boot with headless mode
    v.gui = true
    #v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provider :vmware_fusion do |v|
    # Don't boot with headless mode
    v.gui = true
    #v.vmw["custom-key"] = "value"
  end

  # WinRM
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.network :forwarded_port, guest: 5985, host: 5985

  config.vm.synced_folder "~", "/home"
  config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"

  # This shell provisioner installs chocolatey, ruby, and puppet. Also runs librarian-puppet.
  #config.vm.provision :shell, :path => "shell/main.cmd"

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = "puppet/modules"
    puppet.facter = {
      "domain" => "local",
      "kernel" => "windows",
      "operatingsystem" => "windows",
      "osfamily" => "windows",
    }
  end
end
